version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "php-dump"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dx761exk6ryu"
s3_prefix = "php-dump"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
